Q1. What are the benefits of the built-in array package, if any?

Q2. What are some of the array package's limitations?

Q3. Describe the main differences between the array and numpy packages.

Q4. Explain the distinctions between the empty, ones, and zeros functions.

In [3]:
import numpy as np
np.empty((2,2))

array([[9.33697783e-312, 6.95332756e-310],
       [4.94065646e-324,             nan]])

In [4]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [5]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

In [6]:
import numpy as np
A=np.ones((2,2))
A+5

array([[6., 6.],
       [6., 6.]])

Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

In [7]:
import numpy as np
A=np.ones((2,2))
A+=4
print(A)

[[5. 5.]
 [5. 5.]]


Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

In [15]:
s=np.empty((1,2),dtype='str')
s[0][0]='Manan'
s

array([['M', '']], dtype='<U1')


Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?


In [20]:
x=np.ones((1,2))
y=np.zeros((2,2))
print(x+y)
print(x*y)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


Q10. What is the best way to use a Boolean array to mask another array?

In [25]:
a=np.array((True,False,True,False,True))
b=np.array(((1,2,3,4,5),(1,2,3,4,5)))
b[:,a]

array([[1, 3, 5],
       [1, 3, 5]])

Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

In [47]:
import time
import statistics
import numpy as np
import pandas as pd
a=np.linspace(1,10000)

In [48]:
s=time.time()
print("std",statistics.stdev(a))
e=time.time()
print(e-s)

std 2974.677959008069
0.0029954910278320312


In [49]:
s=time.time()
print("std",numpy.std(a))
e=time.time()
print(e-s)

std 2944.7809393250704
0.0010020732879638672


In [50]:
a=pd.DataFrame(a)
s=time.time()
print("std",pd.DataFrame.std(a))
e=time.time()
print(e-s)

std 0    2974.677959
dtype: float64
0.0039975643157958984


12. What is the dimensionality of a Boolean mask-generated array?