Q1. If you have any, what are your choices for increasing the comparison between different figures on
the same graph?

Q2. Can you explain the benefit of compound interest over a higher rate of interest that does not
compound after reading this chapter?

Q3. What is a histogram, exactly? Name a numpy method for creating such a graph.

Q4. If necessary, how do you change the aspect ratios between the X and Y axes?

In [ ]:
Using set_aspect() method of matplotlib.pyplot.

Q5. Compare and contrast the three types of array multiplication between two numpy arrays: dot
product, outer product, and regular multiplication of two numpy arrays.

In [3]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[1,1],[3,3]])

In [4]:
a

array([[1, 2],
       [3, 4]])

In [5]:
b

array([[1, 1],
       [3, 3]])

In [6]:
a.dot(b)            #matrix multiplication

array([[ 7,  7],
       [15, 15]])

In [7]:
a*b       #elemenet wise ultiplication

array([[ 1,  2],
       [ 9, 12]])

In [8]:
np.outer(a,b)   #every element of a multiply each element of b and so on

array([[ 1,  1,  3,  3],
       [ 2,  2,  6,  6],
       [ 3,  3,  9,  9],
       [ 4,  4, 12, 12]])

Q6. Before you buy a home, which numpy function will you use to measure your monthly mortgage
payment?

Q7. Can string data be stored in numpy arrays? If so, list at least one restriction that applies to this
data.